/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { doc, setDoc } from 'firebase/firestore';
import { db } from '../firebase';
import { UserProfile, PDFSummary } from '../types';
import { exportToPDF } from '../utils/pdfExport';
import { useFeatureGuard } from './FeatureGuard';

interface PDFSummarizerProps {
  userProfile: UserProfile;
  pdfs: PDFSummary[];
  onAddPDF: (pdf: PDFSummary) => void;
  onUpdatePlan?: (plan: 'free' | 'pro' | 'premium') => void;
  onIncrementUsage?: (key: 'aiChatsToday' | 'notesGeneratedThisMonth' | 'pdfSummariesGeneratedThisMonth' | 'quizGeneratedThisMonth' | 'flashcardsGeneratedThisMonth') => void;
}

export default function PDFSummarizer({
  userProfile,
  pdfs,
  onAddPDF,
  onUpdatePlan,
  onIncrementUsage
}: PDFSummarizerProps) {
  const { checkAccessAndRun, UpgradeDialog } = useFeatureGuard(userProfile, 'pdfSummarizer', onUpdatePlan || (() => {}));

  const [selectedPDF, setSelectedPDF] = useState<PDFSummary | null>(null);
  const [fileName, setFileName] = useState('');
  const [pasteContent, setPasteContent] = useState('');
  const [isDragging, setIsDragging] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleSimulatedUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setFileName(file.name);
    setLoading(true);
    const reader = new FileReader();
    reader.onload = (event) => {
      const text = event.target?.result as string;
      if (file.name.endsWith('.pdf')) {
        const cleanText = text.replace(/[^\x20-\x7E\n\r\t]/g, ' ');
        const lines = cleanText.split('\n').map(l => l.trim()).filter(l => l.length > 5);
        setPasteContent(lines.slice(0, 150).join('\n'));
      } else {
        setPasteContent(text);
      }
      setLoading(false);
    };
    reader.readAsText(file);
  };

  const handleGenerateSummary = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!fileName.trim() && !pasteContent.trim()) {
      setError('Please provide a file name or paste text contents.');
      return;
    }

    checkAccessAndRun(async () => {
      const actualFileName = fileName.trim() || "pasted_document.pdf";
      const actualContent = pasteContent.trim();

      setError('');
      setLoading(true);

      try {
        const response = await fetch('/api/generate-summary', {
          method: 'POST',
          headers: { 
            'Content-Type': 'application/json',
            'x-user-uid': userProfile.uid
          },
          body: JSON.stringify({
            fileName: actualFileName,
            fileContent: actualContent
          })
        });

        if (!response.ok) {
          const errData = await response.json().catch(() => ({}));
          throw new Error(errData.error || 'Failed to generate PDF summary from AI.');
        }

        const data = await response.json();
        if (onIncrementUsage) onIncrementUsage('pdfSummariesGeneratedThisMonth');

        const newPDF: PDFSummary = {
          id: 'pdf_' + Date.now(),
          userId: userProfile.uid,
          fileName: actualFileName,
          fileSize: '1.2 MB',
          summary: data.summary || 'Summary generated by AI',
          keyPoints: data.keyPoints || [],
          formulas: data.formulas || [],
          definitions: (data.definitions || []).map((d: any) => `${d.term}: ${d.definition}`),
          revisionNotes: data.revisionNotes || '',
          createdAt: new Date().toISOString()
        };

        // Save to Firestore
        try {
          await setDoc(doc(db, 'pdfs', newPDF.id), newPDF);
        } catch (fErr) {
          console.warn("Firestore save skip:", fErr);
        }

        onAddPDF(newPDF);
        setSelectedPDF(newPDF);

        // Clear inputs
        setFileName('');
        setPasteContent('');
      } catch (err: any) {
        console.error(err);
        setError(err.message || 'Error communicating with Gemini model.');
      } finally {
        setLoading(false);
      }
    });
  };

  const onDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  };

  const onDragLeave = () => {
    setIsDragging(false);
  };

  const onDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    const file = e.dataTransfer.files?.[0];
    if (file) {
      setFileName(file.name);
      setLoading(true);
      const reader = new FileReader();
      reader.onload = (event) => {
        const text = event.target?.result as string;
        if (file.name.endsWith('.pdf')) {
          const cleanText = text.replace(/[^\x20-\x7E\n\r\t]/g, ' ');
          const lines = cleanText.split('\n').map(l => l.trim()).filter(l => l.length > 5);
          setPasteContent(lines.slice(0, 150).join('\n'));
        } else {
          setPasteContent(text);
        }
        setLoading(false);
      };
      reader.readAsText(file);
    }
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      
      {/* Upload Sidebar */}
      <div className="lg:col-span-1 space-y-6">
        
        {/* Upload Container */}
        <div className="study-card p-6 bg-white space-y-4">
          <div className="flex items-center gap-2">
            <span className="text-2xl">📄</span>
            <h3 className="text-md font-bold text-stone-800">Summarize Book / PDF</h3>
          </div>

          <form onSubmit={handleGenerateSummary} className="space-y-4">
            
            {/* Drag & Drop Area */}
            <div 
              onDragOver={onDragOver}
              onDragLeave={onDragLeave}
              onDrop={onDrop}
              className={`border-2 border-dashed rounded-2xl p-6 text-center cursor-pointer transition-all ${isDragging ? 'border-brand-sage bg-brand-sage/5' : 'border-stone-200 hover:border-brand-sage/50'}`}
            >
              <span className="text-3xl block mb-2">📥</span>
              <p className="text-xs font-bold text-stone-700">Drag & Drop PDF file</p>
              <p className="text-[10px] text-stone-400 mt-1 uppercase font-black">Or click to browse</p>
              <input 
                type="file" 
                accept=".pdf"
                onChange={handleSimulatedUpload}
                className="hidden" 
                id="pdf-upload"
              />
              <label htmlFor="pdf-upload" className="mt-3 inline-block bg-stone-100 hover:bg-stone-200 px-3 py-1.5 rounded-xl text-[10px] font-black uppercase tracking-wider text-stone-600 cursor-pointer">
                Select PDF File
              </label>
            </div>

            {fileName && (
              <div className="p-2.5 bg-brand-sage/10 text-brand-sage border border-brand-sage/10 rounded-xl text-xs font-bold flex items-center justify-between">
                <span className="truncate">📎 {fileName}</span>
                <button type="button" onClick={() => { setFileName(''); setPasteContent(''); }} className="text-[10px] uppercase font-black text-red-500">Reset</button>
              </div>
            )}

            {/* Paste Alternative */}
            <div className="space-y-1">
              <div className="flex justify-between">
                <label className="text-[10px] uppercase tracking-widest font-black text-stone-400">Extracted / Pasted Text Context</label>
              </div>
              <textarea 
                value={pasteContent}
                onChange={(e) => setPasteContent(e.target.value)}
                rows={5}
                required
                placeholder="Paste the extracted PDF text or book chapter contents here to summarize immediately..."
                className="w-full bg-[#F5F5F0] border border-black/5 focus:border-[#5A5A40] rounded-xl px-3 py-2.5 text-xs outline-none transition-all resize-none"
              />
            </div>

            {error && <p className="text-[10px] text-red-500 font-bold">⚠️ {error}</p>}

            <button
              type="submit"
              disabled={loading}
              className="w-full bg-[#5A5A40] hover:bg-[#494933] text-white py-3 rounded-xl font-bold text-xs uppercase tracking-wider transition-all shadow-md cursor-pointer disabled:opacity-50"
            >
              {loading ? 'Analyzing with Gemini...' : 'Generate AI Summary'}
            </button>
          </form>
        </div>

        {/* History repository */}
        <div className="study-card p-6 bg-white">
          <p className="text-[10px] uppercase tracking-widest text-stone-400 font-black mb-4">Uploaded Summaries</p>
          <div className="space-y-2 max-h-48 overflow-y-auto pr-1">
            {pdfs.length > 0 ? pdfs.map(pdf => (
              <div
                key={pdf.id}
                onClick={() => setSelectedPDF(pdf)}
                className={`p-3 rounded-xl text-xs font-bold flex items-center justify-between cursor-pointer border transition-all ${selectedPDF?.id === pdf.id ? 'bg-[#5A5A40]/10 text-brand-sage border-[#5A5A40]/20' : 'border-transparent text-stone-500 hover:bg-stone-50'}`}
              >
                <span className="truncate">📄 {pdf.fileName}</span>
                <span className="text-[9px] text-stone-400 font-mono">{pdf.fileSize}</span>
              </div>
            )) : (
              <p className="text-[11px] text-stone-400 font-medium text-center py-4">No PDF summaries generated yet.</p>
            )}
          </div>
        </div>

      </div>

      {/* Main Panel Summary Display */}
      <div className="lg:col-span-2 space-y-6">
        {selectedPDF ? (
          <div className="study-card p-8 bg-white space-y-6">
            
            {/* Header */}
            <div className="flex justify-between items-start border-b border-stone-100 pb-5">
              <div className="space-y-1">
                <span className="inline-block px-2.5 py-0.5 bg-brand-sand/10 text-[#8B5E3C] rounded-full text-[10px] font-black uppercase tracking-wider">
                  AI Study Packet Summary
                </span>
                <h2 className="text-2xl font-serif italic text-stone-800 font-bold">{selectedPDF.fileName}</h2>
                <p className="text-[10px] text-stone-400 font-mono uppercase tracking-widest">
                  Analyzed on {new Date(selectedPDF.createdAt).toLocaleDateString()}
                </p>
              </div>
              <button 
                onClick={() => {
                  exportToPDF({
                    title: selectedPDF.fileName,
                    subtitle: `Analyzed on ${new Date(selectedPDF.createdAt).toLocaleDateString()} - File Size: ${selectedPDF.fileSize}`,
                    summary: selectedPDF.summary,
                    keyPoints: selectedPDF.keyPoints,
                    formulas: selectedPDF.formulas,
                    definitions: selectedPDF.definitions,
                    extraText: selectedPDF.revisionNotes ? [
                      { label: "Interactive Revision Notes", content: selectedPDF.revisionNotes }
                    ] : undefined
                  });
                }}
                className="px-3 py-1.5 bg-[#5A5A40] text-white rounded-xl text-[10px] font-black uppercase tracking-wider hover:bg-[#494933] transition-colors cursor-pointer flex items-center gap-1 shadow-sm"
              >
                📄 Download PDF
              </button>
            </div>

            {/* High Level Summary */}
            <div className="space-y-2">
              <h4 className="text-xs uppercase tracking-widest font-black text-stone-400">Chapter Summaries & Overview</h4>
              <p className="text-stone-600 text-xs leading-relaxed bg-[#FDFBF7] p-4 rounded-2xl border border-stone-100">
                {selectedPDF.summary}
              </p>
            </div>

            {/* Key Points */}
            {selectedPDF.keyPoints && selectedPDF.keyPoints.length > 0 && (
              <div className="space-y-2">
                <h4 className="text-xs uppercase tracking-widest font-black text-stone-400">Critical Insight Bulletpoints</h4>
                <ul className="space-y-1.5">
                  {selectedPDF.keyPoints.map((pt, i) => (
                    <li key={i} className="text-xs text-stone-600 flex items-start gap-2.5">
                      <span className="text-brand-sage mt-0.5">✦</span>
                      <span>{pt}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Formulas */}
            {selectedPDF.formulas && selectedPDF.formulas.length > 0 && (
              <div className="space-y-2">
                <h4 className="text-xs uppercase tracking-widest font-black text-stone-400">Identified Formulas & Equations</h4>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                  {selectedPDF.formulas.map((formula, i) => (
                    <div key={i} className="p-3 bg-[#5A5A40]/5 border border-[#5A5A40]/10 rounded-xl font-mono text-xs text-brand-sage flex items-center justify-center text-center">
                      {formula}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Glossary definitions */}
            {selectedPDF.definitions && selectedPDF.definitions.length > 0 && (
              <div className="space-y-2">
                <h4 className="text-xs uppercase tracking-widest font-black text-stone-400">Glossary of Key Terms</h4>
                <div className="divide-y divide-stone-100 bg-[#FDFBF7] rounded-2xl border border-stone-100 overflow-hidden">
                  {selectedPDF.definitions.map((def, i) => {
                    const splitIdx = def.indexOf(':');
                    const term = splitIdx !== -1 ? def.substring(0, splitIdx) : "Concept";
                    const definition = splitIdx !== -1 ? def.substring(splitIdx + 1) : def;
                    return (
                      <div key={i} className="p-3 text-xs">
                        <strong className="text-stone-800 block sm:inline-block sm:w-28 font-bold">{term}:</strong>
                        <span className="text-stone-500 sm:pl-2">{definition}</span>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}

            {/* Revision Notes */}
            {selectedPDF.revisionNotes && (
              <div className="space-y-2">
                <h4 className="text-xs uppercase tracking-widest font-black text-stone-400">Interactive Revision Notes</h4>
                <div className="p-4 bg-stone-50 rounded-2xl border border-stone-100 text-xs text-stone-600 whitespace-pre-line leading-relaxed">
                  {selectedPDF.revisionNotes}
                </div>
              </div>
            )}

          </div>
        ) : (
          <div className="study-card p-12 bg-white flex flex-col items-center justify-center text-center space-y-3 min-h-[400px]">
            <span className="text-4xl">📄</span>
            <h3 className="text-lg font-serif italic text-stone-700">No Document summary active</h3>
            <p className="text-stone-400 text-xs max-w-sm">Upload a PDF or paste book text. AI will automatically parse equations, glossary lists, bullet-point revisions, and long dockets, structured with natural study layouts!</p>
          </div>
        )}
      </div>

      {UpgradeDialog}
    </div>
  );
}
